name = "human-in-the-loop"
main = "./src/server.ts"
compatibility_date = "2025-02-14"

assets = {}


[[durable_objects.bindings]]
name = "HumanInTheLoop"
class_name = "HumanInTheLoop"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HumanInTheLoop"]
